name: blurbotest
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6696535
title: This is a test. Reserving judgment.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefe3a'
    - '#ffffff'
    - '#161616'
    - '#47671c'
    - '#f0c92e'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
