name: blurbotest
favicon: null
layout_spectrum: 0.6307611444499344
typography_spectrum: 0.8263430229853839
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fddcc2'
    - '#d4ad8c'
    - '#272e07'
    - '#8a662f'
    - '#6a4d0c'
  brandStrength: 0.375
  lightness: 0.125
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
