title: What a staggering disappointment.
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0
  rhythmicContrast: 1
  brandColors:
    - '#ffffff'
    - '#7466d3'
    - '#6a90c8'
    - '#44bfc9'
    - '#9bb5da'
  lightness: 0.9265233
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: blurbotest
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8237754
layout_spectrum: 1
