name: blurbotest
favicon: null
layout_spectrum: 0.48995
typography_spectrum: 0.6696535
title: This is a test. Reserving judgment.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fddcc2'
    - '#d4ad8c'
    - '#272e07'
    - '#8a662f'
    - '#6a4d0c'
  brandStrength: 0.0625
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
